language: python

python:
   - "3.5"
# install dependencies
install:
   - pip install -r requirements.txt
# run tests
script:
   - export PYTHONPATH=$PYTHONPATH:$(pwd)
   - python app/tests/app-test.py